#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
zncpass = "6FF0D8B2E44559189BCDEC89A5BD0A76E6933BB4627616C84DA0A9BADF3179581D6B10B5FF6BD029E895B2610854F89BE154DB39955F7C6E5F5811CC2AB2436FE5380D46F6E020EEEA8821B53BC19EF24DA8A62E2C8F65BE61A20B8911669D6E3400FD9FE87A463AC7"
