#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
zncpass = "2C66059A8436A9833CC1371A8ADADBF69880B49D9CEED4AC8BB109AF495BB3A48B9C3862B2957DCF70415268B52ECAB43BCEB572DC708A744F5C9C235A3AABE6D327334946403E6B1B1DE0AF56160F9AB6F8F786BBFAFFBFCD9F0D9067905903783B6422A6CFE15FD0611F752A9F55DA85D5C0"
