[manager]
ratio           = [2, 2, 4]
show_hidden     = true
show_symlink    = true
title_format    = "{cwd}"
sort_by         = "alphabetical"
sort_dir_first  = true
linemode        = "size"

[preview]
wrap            = "no"
tab_size        = 2

[input]
cursor_blink    = true
