[mgr]
ratio = [2, 2, 4]
show_hidden = true
show_symlink = true
title_format = "{cwd}"
sort_by = "alphabetical"
linemode = "size"

[preview]
wrap = "yes"
image_quality = 90
tab_size = 2

[input]
cursor_blink = true
