return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  config = function()
    require('nvim-treesitter').setup {
      ensure_installed = {
        'lua',
        'javascript',
        'bash',
        'css',
        'csv',
        'git_config',
        'gitcommit',
        'gitignore',
        'gpg',
        'html',
        'hyprlang',
        'http',
        'json',
        'jsonc',
        'liquid',
        'nginx',
        'php',
        'powershell',
        'python',
        'regex',
        'scss',
        'sql',
        'ssh_config',
        'svelte',
        'toml',
        'tsv',
        'tsx',
        'typescript',
        'vim',
        'vue',
        'yaml',
      },
      auto_install = true,
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
      },
    }
  end,
}
