return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  opts = {
    animate = { enabled = true },
    bigfile = { enabled = true },
    bufdelete = { enabled = true },
    dashboard = {
      enabled = true,
      width = 75,
      sections = {
        {
          pane = 1,
          section = 'terminal',
          cmd = 'ascii-image-converter ~/.config/avatar/hacker.webp --threshold 1 -bCW75',
          hl = 'header',
          height = 21,
          padding = 1,
        },
        {
          pane = 2,
          section = 'keys',
          padding = 1,
        },
        {
          pane = 2,
          icon = ' ',
          title = 'Recent Files',
          section = 'recent_files',
          indent = 2,
          padding = 1,
        },
        {
          pane = 2,
          icon = ' ',
          title = 'Projects',
          section = 'projects',
          indent = 2,
        },
      },
      preset = {
        keys = {
          {
            icon = ' ',
            key = 'f',
            desc = 'Find File',
            action = ':lua Snacks.dashboard.pick(\'files\')',
          },
          {
            icon = ' ',
            key = 'n',
            desc = 'New File',
            action = ':ene | startinsert',
          },
          {
            icon = ' ',
            key = 'g',
            desc = 'Find Text',
            action = ':lua Snacks.dashboard.pick(\'live_grep\')',
          },
          {
            icon = '󰙅 ',
            key = 'e',
            desc = 'Explorer',
            action = ':lua Snacks.picker.explorer()',
          },
          {
            icon = ' ',
            key = 'r',
            desc = 'Recent Files',
            action = ':lua Snacks.dashboard.pick(\'oldfiles\')',
          },
          {
            icon = ' ',
            key = 'l',
            desc = 'Lazy Check',
            action = ':Lazy check',
          },
          {
            icon = ' ',
            key = 'm',
            desc = 'Mason Update',
            action = ':Mason',
          },
        },
      },
    },
    debug = { enabled = true },
    dim = { enabled = true },
    explorer = {
      enabled = true,
    },
    git = { enabled = true },
    gitbrowse = { enabled = true },
    image = { enabled = true },
    indent = { enabled = true },
    input = { enabled = true },
    layout = { enabled = true },
    lazygit = { enabled = true },
    notifier = { enabled = true },
    notify = { enabled = true },
    picker = {
      enabled = true,
      layouts = {
        sidebar = {
          preview = 'main',
          layout = {
            backdrop = false,
            width = 30,
            min_width = 30,
            height = 0,
            position = 'left',
            border = 'none',
            box = 'vertical',
            {
              win = 'input',
              height = 1,
              border = 'rounded',
              title = '{title} {live} {flags}',
              title_pos = 'center',
            },
            {
              win = 'list',
              border = 'none',
            },
            {
              win = 'preview',
              title = '{preview}',
              height = 0.4,
              border = 'top',
            },
          },
        },
      },
    },
    profiler = { enabled = true },
    quickfile = { enabled = true },
    rename = { enabled = true },
    scope = { enabled = true },
    scratch = { enabled = true },
    scroll = { enabled = true },
    statuscolumn = {
      enabled = true,
      left = { 'mark', 'sign' },
      right = { 'fold', 'git' },
      folds = {
        open = true,
        git_hl = true,
      },
      git = {
        patterns = { 'GitSign', 'MiniDiffSign' },
      },
      refresh = 50,
    },
    terminal = { enabled = true },
    toggle = { enabled = true },
    util = { enabled = true },
    win = { enabled = true },
    words = { enabled = true },
    zen = { enabled = true },
  },
}
