return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  opts = {
    auto_install = true,
    highlight = {
      enabled = true,
    },
    indent = {
      enabled = true,
    },
    ensure_installed = {
      'arduino',
      'astro',
      'bash',
      'c',
      'c_sharp',
      'cmake',
      'css',
      'csv',
      'diff',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitcommit',
      'gitignore',
      'go',
      'gpg',
      'graphql',
      'html',
      'http',
      'hyprlang',
      'javascript',
      'jsdoc',
      'json',
      'jsonc',
      'liquid',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'nginx',
      'php',
      'phpdoc',
      'powershell',
      'printf',
      'pug',
      'python',
      'regex',
      'robot',
      'robots',
      'scss',
      'sql',
      'ssh_config',
      'svelte',
      'toml',
      'tsv',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'vue',
      'xml',
      'yaml',
    },
  },
}
