return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  config = function()
    require('nvim-treesitter').setup {
      additional_vim_regex_highlighting = false,
      ensure_installed = {
        auto_install = true,
        sync_install = false,
        highlight = {
          enable = true,
        },
        indent = {
          enable = true,
        },
        'bash',
        'c',
        'css',
        'csv',
        'diff',
        'git_config',
        'gitcommit',
        'gitignore',
        'gpg',
        'html',
        'http',
        'hyprlang',
        'javascript',
        'json',
        'jsonc',
        'liquid',
        'lua',
        'luadoc',
        'markdown',
        'markdown_inline',
        'nginx',
        'php',
        'powershell',
        'python',
        'query',
        'regex',
        'scss',
        'sql',
        'ssh_config',
        'svelte',
        'toml',
        'tsv',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'vue',
        'yaml',
      },
    }
  end,
}
